# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Meta Description", name: "meta_description", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      # Start custom fields
      - {label: "Area Name", name: "area", widget: "string", required: true}
      - {label: "Town", name: "town", widget: "string", required: true}
      - {label: "State", name: "state", widget: "string", required: true}
      - {label: "Map JSON", name: "map", widget: "map", required: false}
      - {label: "Latitude", name: "latitude", widget: "string", required: false}
      - {label: "Longitude", name: "longitude", widget: "string", required: false}
      - {label: "Area Website", name: "website", widget: "string", required: false}
      - {label: "Area Map Link", name: "area-map", widget: "string", required: false}
      - {label: "Google Maps Link", name: "google-link", widget: "string", required: false}
      - {label: "Distance", hint: "in miles", name: "distance", widget: "number", step: .1, min: 0, max: 9999, required: false}
      - {label: "Duration", hint: "in hours", name: "duration", widget: "number", step: .1, min: 0, max: 9999, required: false}
      - label: "Rating"
        name: "rating"
        widget: "number"
        required: false
        options: ["1", "2", "3", "4", "5"]
      - label: "Difficulty"
        name: "difficulty"
        widget: "number"
        step: 1
        min: 1
        max: 5
        required: false
        options: ["1", "2", "3", "4", "5"]
      - label: "Flynn's Happiness Level"
        name: "happiness"
        widget: "number"
        step: 1
        min: 1
        max: 5
        required: false
        options: ["1", "2", "3", "4", "5"]
    # PAGES
  - name: "page"
    label: "Page"
    folder: "pages"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Meta Description", name: "meta_description", widget: "string", required: false}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
